name: Build proxy

on:
  push:
    tags:
      - 'coa*'
    branches:
      - feature/*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TAG: v100.0.0

jobs:
  apicli:
    strategy:
      fail-fast: true
      matrix:
        os: [ linux ]
        arch: [ amd64, arm64 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - name: Login to ghcr
        uses: docker/login-action@v2
        with:

          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: Dockerfile
          tags: docker.io/${{ secrets.DOCKER_USER }}/${{ github.repository_name }}-apicli:${{ env.TAG }}
          args: |
            TAG=${{ github.ref }}
            TARGETARCH=${{ matrix.arch }}
            TARGETOS=${{ matrix.os }}
            DIR=apicli
  scheduler:
    strategy:
      fail-fast: true
      matrix:
        os: [ linux ]
        arch: [ amd64, arm64 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - name: Login to ghcr
        uses: docker/login-action@v2
        with:
           
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: Dockerfile
          tags: docker.io/${{ secrets.DOCKER_USER }}/${{ github.repository_name }}-scheduler:${{ env.TAG }}
          args: |
            TAG=${{ github.ref }}
            TARGETARCH=${{ matrix.arch }}
            TARGETOS=${{ matrix.os }}
            DIR=scheduler
  executor:
    strategy:
      fail-fast: true
      matrix:
        os: [ linux ]
        arch: [ amd64, arm64 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - name: Login to ghcr
        uses: docker/login-action@v2
        with:
           
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: Dockerfile
          tags: docker.io/${{ secrets.DOCKER_USER }}/${{ github.repository_name }}-executor:${{ env.TAG }}
          args: |
            TAG=${{ github.ref }}
            TARGETARCH=${{ matrix.arch }}
            TARGETOS=${{ matrix.os }}
            DIR=executor
  balancer:
    strategy:
      fail-fast: true
      matrix:
        os: [ linux ]
        arch: [ amd64, arm64 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - name: Login to ghcr
        uses: docker/login-action@v2
        with:
           
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: Dockerfile
          tags: docker.io/${{ secrets.DOCKER_USER }}/${{ github.repository_name }}-balancer:${{ env.TAG }}
          args: |
            TAG=${{ github.ref }}
            TARGETARCH=${{ matrix.arch }}
            TARGETOS=${{ matrix.os }}
            DIR=balancer
  apiserver:
    strategy:
      fail-fast: true
      matrix:
        os: [ linux ]
        arch: [ amd64, arm64 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - name: Login to ghcr
        uses: docker/login-action@v2
        with:
           
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: Dockerfile
          tags: docker.io/${{ secrets.DOCKER_USER }}/${{ github.repository_name }}-apiserver:${{ env.TAG }}
          args: |
            TAG=${{ github.ref }}
            TARGETARCH=${{ matrix.arch }}
            TARGETOS=${{ matrix.os }}
            DIR=apiserver
  enri:
    strategy:
      fail-fast: true
      matrix:
        os: [ linux ]
        arch: [ amd64, arm64 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - name: Login to ghcr
        uses: docker/login-action@v2
        with:
           
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: Dockerfile
          tags: docker.io/${{ secrets.DOCKER_USER }}/${{ github.repository_name }}-enri:${{ env.TAG }}
          args: |
            TAG=${{ github.ref }}
            TARGETARCH=${{ matrix.arch }}
            TARGETOS=${{ matrix.os }}
            DIR=enri
  proxy:
    strategy:
      fail-fast: true
      matrix:
        os: [ linux ]
        arch: [ amd64, arm64 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - name: Login to ghcr
        uses: docker/login-action@v2
        with:
           
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: Dockerfile
          tags: docker.io/${{ secrets.DOCKER_USER }}/${{ github.repository_name }}-proxy:${{ env.TAG }}
          args: |
            TAG=${{ github.ref }}
            TARGETARCH=${{ matrix.arch }}
            TARGETOS=${{ matrix.os }}
            DIR=proxy
  anzi:
    strategy:
      fail-fast: true
      matrix:
        os: [linux,darwin, windows]
        arch: [amd64, arm64]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - name: Login to ghcr
        uses: docker/login-action@v2
        with:
           
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: Dockerfile
          tags: docker.io/${{ secrets.DOCKER_USER }}/${{ github.repository_name }}-anzi:${{ env.TAG }}
          args: |
            TAG=${{ github.ref }}
            TARGETARCH=${{ matrix.arch }}
            TARGETOS=${{ matrix.os }}
            DIR=anzi
  gui:
    strategy:
      fail-fast: true
      matrix:
        os: [ linux ]
        arch: [ amd64, arm64 ]
    runs-on: ubuntu-latest
    needs: [proxy, anzi, enri, apiserver, balancer, executor, scheduler, apicli]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - name: Login to ghcr
        uses: docker/login-action@v2
        with:
           
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: Dockerfile
          tags: docker.io/${{ secrets.DOCKER_USER }}/${{ github.repository_name }}-gui:${{ env.TAG }}
          args: |
            TAG=${{ github.ref }}
            TARGETARCH=${{ matrix.arch }}
            TARGETOS=${{ matrix.os }}
            DIR=web